# -*- coding: utf-8 -*-
"""cricket_player_ performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXH1NkDnI5w3HqpTz7gjY3Kfvjs6bWBq

# Cricket Player Performance

## 1. Import Tools
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer

from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# %matplotlib inline
pd.set_option('display.max_columns', None)

"""## 2. Import Data"""

df = pd.read_csv("E://Sam - 3//ML//Mini project//cricket_player_ performance//code//Data//cricket_player_ performance.csv")

"""## 3. HBIS — Head, Basic Info & Shape"""

# Head - first 5 rows
df.head()

# Basic Info - column dtypes & non-null counts
df.info()

# Shape - rows x columns
print("Shape:", df.shape)

# Statistical Summary
df.describe()

"""## 4. Train Data — Clean, EDA, Label Encode, Split

### 4.1 Data Cleaning (Missing Values & Duplicates)
"""

# Replace placeholder characters with NaN
df.replace('?', np.nan, inplace=True)

# Check missing values
print("Missing values per column:\n", df.isnull().sum())
print("\nTotal missing values:", df.isnull().sum().sum())

# Check duplicates
print("\nDuplicate rows:", df.duplicated().sum())
df.drop_duplicates(inplace=True)

# Separate numeric and categorical columns
numerical_cols = df.select_dtypes(include=['number']).columns
categorical_cols = df.select_dtypes(include=['object', 'string']).columns

# Impute (safety step, applies only if missing values exist)
if df[numerical_cols].isnull().sum().sum() > 0:
    df[numerical_cols] = SimpleImputer(strategy='mean').fit_transform(df[numerical_cols])

if df[categorical_cols].isnull().sum().sum() > 0:
    df[categorical_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[categorical_cols])

print("Remaining missing values:", df.isnull().sum().sum())

"""### 4.2 Feature Engineering — Extract Date Parts"""

df['Date'] = pd.to_datetime(df['Date'])
df['Match_Year'] = df['Date'].dt.year
df['Match_Month'] = df['Date'].dt.month
df.drop(columns=['Date'], inplace=True)
df.head()

"""### 4.3 Exploratory Data Analysis (EDA)"""

# Target class distribution
print(df['Match_Result'].value_counts())

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Match_Result')
plt.title("Match Result Distribution")
plt.show()

# Match type distribution
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Match_Type')
plt.title("Match Type Distribution")
plt.show()

# Correlation among numeric features
plt.figure(figsize=(6, 5))
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

"""### 4.4 Label Encoding (Categorical Columns)"""

categorical_cols = df.select_dtypes(include=['object', 'string']).columns
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

print("Match_Result classes:", dict(enumerate(label_encoders['Match_Result'].classes_)))
df.head()

"""### 4.5 Feature Scaling"""

target = 'Match_Result'
numerical_cols = df.select_dtypes(include=['number']).columns
scale_cols = [c for c in numerical_cols if c != target]

scaler = MinMaxScaler()
df[scale_cols] = scaler.fit_transform(df[scale_cols])
df.head()

"""### 4.6 Train-Test Split"""

features = df.columns[df.columns != target]
X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

"""## 5. Fit Algorithms on Train Dataset & Evaluate One by One

### 5.1 SVM (Support Vector Machine)
"""

svm_model = SVC(kernel='rbf', C=1, gamma='scale')
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

print("Confusion Matrix (SVM):\n", confusion_matrix(y_test, y_pred_svm))
print("\nAccuracy (SVM):", round(accuracy_score(y_test, y_pred_svm) * 100, 2), "%")
print("\nClassification Report (SVM):\n", classification_report(y_test, y_pred_svm))

"""### 5.2 Naive Bayes (NB)"""

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)

print("Confusion Matrix (Naive Bayes):\n", confusion_matrix(y_test, y_pred_nb))
print("\nAccuracy (Naive Bayes):", round(accuracy_score(y_test, y_pred_nb) * 100, 2), "%")
print("\nClassification Report (Naive Bayes):\n", classification_report(y_test, y_pred_nb))

"""### 5.3 K-Nearest Neighbors (KNN)"""

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)

print("Confusion Matrix (KNN):\n", confusion_matrix(y_test, y_pred_knn))
print("\nAccuracy (KNN):", round(accuracy_score(y_test, y_pred_knn) * 100, 2), "%")
print("\nClassification Report (KNN):\n", classification_report(y_test, y_pred_knn))

"""### 5.4 Decision Tree"""

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("Confusion Matrix (Decision Tree):\n", confusion_matrix(y_test, y_pred_dt))
print("\nAccuracy (Decision Tree):", round(accuracy_score(y_test, y_pred_dt) * 100, 2), "%")
print("\nClassification Report (Decision Tree):\n", classification_report(y_test, y_pred_dt))

"""### 5.5 Random Forest"""

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("Confusion Matrix (Random Forest):\n", confusion_matrix(y_test, y_pred_rf))
print("\nAccuracy (Random Forest):", round(accuracy_score(y_test, y_pred_rf) * 100, 2), "%")
print("\nClassification Report (Random Forest):\n", classification_report(y_test, y_pred_rf))

"""## 6. Model Comparison (Evaluation Summary)"""

results = {
    'SVM': accuracy_score(y_test, y_pred_svm),
    'Naive Bayes': accuracy_score(y_test, y_pred_nb),
    'KNN': accuracy_score(y_test, y_pred_knn),
    'Decision Tree': accuracy_score(y_test, y_pred_dt),
    'Random Forest': accuracy_score(y_test, y_pred_rf),
}

comparison_df = pd.DataFrame(list(results.items()), columns=['Model', 'Accuracy'])
comparison_df['Accuracy (%)'] = (comparison_df['Accuracy'] * 100).round(2)
comparison_df = comparison_df.sort_values('Accuracy (%)', ascending=False)
comparison_df

plt.figure(figsize=(9, 5))
sns.barplot(data=comparison_df, x='Accuracy (%)', y='Model', hue='Model', palette='mako', legend=False)
plt.title("Model Accuracy Comparison")
plt.xlabel("Accuracy (%)")
plt.tight_layout()
plt.show()

"""## 7. Prediction

Best-performing model (highest accuracy) use karke test set ke pehle 10 samples ki prediction actual values ke saath compare kar rahe hain.
"""

best_model_name = comparison_df.iloc[0]['Model']
model_lookup = {
    'SVM': svm_model,
    'Naive Bayes': nb_model,
    'KNN': knn_model,
    'Decision Tree': dt_model,
    'Random Forest': rf_model,
}
best_model = model_lookup[best_model_name]
print(f"Best Model: {best_model_name}")

y_pred_best = best_model.predict(X_test)

result_table = X_test.copy()
result_table['Actual_Match_Result'] = label_encoders['Match_Result'].inverse_transform(y_test)
result_table['Predicted_Match_Result'] = label_encoders['Match_Result'].inverse_transform(y_pred_best)

result_table[['Actual_Match_Result', 'Predicted_Match_Result']].head(10)

"""## 8. Visualizations (Matplotlib)"""

### Scatter Plot - Runs vs Strike Rate colored by Match Result ###
plt.figure(figsize=(8, 6))
sns.scatterplot(data=df, x='Runs', y='Strike_Rate', hue='Match_Result', palette='Set1', alpha=0.6)
plt.title("Scatter Plot: Runs vs Strike Rate (by Match Result)")
plt.show()

### Histograms of Key Numerical Attributes (Grid Layout) ###
import matplotlib.pyplot as plt
import seaborn as sns

hist_cols = ['Runs', 'Balls_Faced', 'Strike_Rate', 'Economy_Rate', 'Player_Impact_Score']

colors = ['red', 'green', 'blue', 'orange', 'purple']

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

for i, col in enumerate(hist_cols):
    sns.histplot(
        df[col],
        bins=30,
        kde=True,
        ax=axes[i],
        color=colors[i],
        edgecolor='black',
        alpha=0.8
    )
    axes[i].set_title(f"Histogram of {col}", fontsize=11)
    axes[i].grid(True, linestyle='--', alpha=0.5)

axes[5].axis('off')

plt.tight_layout()
plt.show()

### Box Plot - Match_Result distribution ###
plt.figure(figsize=(6, 4))
sns.boxplot(y=df['Match_Result'], color='skyblue')
plt.title("Box Plot of Match_Result (encoded)", fontsize=14)
plt.ylabel("Match_Result")
plt.tight_layout()
plt.show()

### Box Plots without Outliers - Key Numeric Stats ###
numerical_columns = ['Runs', 'Balls_Faced', 'Strike_Rate', 'Player_Impact_Score', 'Target_Score']
fig, axes = plt.subplots(nrows=1, ncols=5, figsize=(18, 5))
for idx, col in enumerate(numerical_columns):
    data = df[col].dropna()
    axes[idx].boxplot(data, showfliers=False)
    axes[idx].set_title(col)
plt.tight_layout()
plt.show()

### Confusion Matrix Heatmaps for all models ###
fig, axes = plt.subplots(2, 3, figsize=(16, 9))
axes = axes.flatten()

preds = {
    'SVM': y_pred_svm,
    'Naive Bayes': y_pred_nb,
    'KNN': y_pred_knn,
    'Decision Tree': y_pred_dt,
    'Random Forest': y_pred_rf,
}

for i, (name, pred) in enumerate(preds.items()):
    cm = confusion_matrix(y_test, pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[i], cbar=False)
    axes[i].set_title(name)
    axes[i].set_xlabel("Predicted")
    axes[i].set_ylabel("Actual")

axes[5].axis('off')
plt.tight_layout()
plt.show()

